### ISSUE TITLE
data sources

### ISSUE THREAD

**Issue by DesalegnChala** [uio-mana/CWR-Hackathon#5] opened 2024-01-24 09:19 UTC
1) What additional data sources can we use for occurrence data? can you please mention them and also if there any function to access them. 
2) additional layers such as protected areas of the world and any function to easily access them. 
################## potential data sources - notes from discussions ###############
1)	Genesys – the accessions in situ – GBIF is more curated – data should be filtered 
Weighing the data – Filtering by date 
2)	WIEWS
3)	Herbaria – open herbarium – an open data base where major herbaria are digitized and data are made available 
4)	Symbiota –  https://symbiota.org/
5)	The botanical gardens conservation database - can potentially be ex situ conservation - need caution 
7)	Protected planet.
######### abiotic stresses #################
 Aridity, Soil Ph, Soil salinity from harmonized data sources

**Comment by ErikKusch** [comment] 2024-01-24 09:19
duplicate of #2

**Closed as completed by ErikKusch** 2024-01-24 09:19 UTC
